### ISSUE TITLE
Definição canal de discussão sobre o código de conduta

### ISSUE THREAD

**Issue by gilsondev** [pythonbrasil/codigo-de-conduta#1]
Definir no arquivo, ou uma forma de divulgar alguma thread ou canal (seja slack, telegram, etc), reservado para a discussão do código de conduta.

**Comment by jtemporal** [comment]
Acho que é válido mencionar que discussões referentes ao CdC agora [estão ocorrendo nesta thread de emails aberta](https://groups.google.com/d/topic/apyb-associados/RXR_0gosYbY) com o envio do novo CdC aprovado pelo conselho deliberativo.

**Comment by rougeth** [comment]
Fechando essa issue. Desde que o CdC foi escrito, ele tem sido aplicado nos ambientes da Python Brasil oficialmente mantidos pela organização, incluindo, por exemplo, grupos em aplicativos de mensagens online.

Se quiserem continuar com a discussão, recomendo usarem o [apyb/comunidade](https://github.com/apyb/comunidade/discussions).

👋
